name: run-tests

on:
    push:
    schedule:
        - cron: '0 0 * * *'

jobs:
    laravel-version-tests:

        name: Laravel ver test - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench}} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [7.4]
                testbench: [^4.0, 3.8.*, 3.7.*, 3.6.*, 3.5.*, 3.4.*, 3.3.*]
                dependency-prefer: [prefer-stable, prefer-lowest]
                include:
                    -   testbench: ^4.0
                        phpunit: ^8.4 || ^9.0
                    -   testbench: 3.8.*
                        phpunit: ^7.5 || ^8.0
                    -   testbench: 3.7.*
                        phpunit: ^7.0
                    -   testbench: 3.6.*
                        phpunit: ^7.0
                    -   testbench: 3.5.*
                        phpunit: ~6.0
                    -   testbench: 3.4.*
                        phpunit: ~5.7
                    -   testbench: 3.3.*
                        phpunit: ~5.5
                    # testbench <= 3.2 requires phpunit < 5.5. It extends upon PHPUnit_Framework_TestCase. However the unit tests in this package extend from PHPUnit\Framework\TestCase which is only available in phpunit >= 5.5

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, bcmath, intl
                    coverage: none

            # find out composer's cache directory on the current os - for the "Cache composer dependencies" step below
            -   name: Determine composer's cache directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies (composer)
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

            -   name: Install dependencies (composer)
                run: |
                    composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit

    php-version-tests:

        name: PHP ver test - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench}} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                php: [7.4, 7.3, 7.2, 7.1]
                testbench: [3.8.*]
                dependency-prefer: [prefer-stable, prefer-lowest]
                include:
                    -   testbench: 3.8.*
                        phpunit: ^7.5 || ^8.0
                exclude:
                    # the output for some numbers contains unexpected characters (they look correct but are different to every other os/php combination)
                    -   php: 7.1
                        os: windows-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, bcmath, intl
                    coverage: none

            # find out composer's cache directory on the current os - for the "Cache composer dependencies" step below
            -   name: Determine composer's cache directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies (composer)
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

            -   name: Install dependencies (composer)
                run: |
                    composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit
